[package]
name = "suttabot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.12.*", features = ["macros", "auto-send"] }
log = "0.4.*"
pretty_env_logger = "0.5.*"
tokio = { version =  "1.29.*", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0.*"
sqlx = { version = "0.7", features = [ "runtime-tokio", "sqlite" ] }
chrono = "0.4.35"
