[package]
name = "suttabot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.12.2", features = ["macros", "auto-send"] }
log = "0.4.21"
pretty_env_logger = "0.5.0"
tokio = { version =  "1.37.0", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0.83"
sqlx = { version = "0.7.4", features = [ "runtime-tokio", "sqlite" ] }
chrono = "0.4.38"
rand = "0.8.5"
thiserror = "1.0.61"
